name: cicd
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 15.x ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - uses: actions/setup-node@v1
        name: Node ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - name: setup project
        run: npm install

      - name: run tests
        run: npm test

  code-quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - uses: actions/setup-node@v1
        name: Node ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - name: run code quality checks
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  package:
    runs-on: ubuntu-latest
    needs: [code-quality, tests]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-node@v1
        name: Node ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - name: get artifact version
        id: image_version_step
        run: echo "::set-output name=ARTIFACT_VERSION::$(cat package.json | jq .version | tr -d \")"

      - name: echo artifact version
        run: echo ${{ steps.image_version_step.outputs.ARTIFACT_VERSION }}

      - name: build docker image
        run: |
          docker build -t generalmeow/bigly-ws-prices:${{ steps.image_version_step.outputs.ARTIFACT_VERSION }} .
          docker tag generalmeow/bigly-ws-prices:${{ steps.image_version_step.outputs.ARTIFACT_VERSION }} generalmeow/bigly-ws-prices:latest

      - name: scan
        uses: anchore/scan-action@v2
        with:
          image: "generalmeow/bigly-ws-prices:latest"
#          fail-build: true
#          severity-cutoff: critical

      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: upload docker image
        run: |
          docker push generalmeow/bigly-ws-prices:${{ steps.image_version_step.outputs.ARTIFACT_VERSION }}
          docker push generalmeow/bigly-ws-prices:latest
